### ISSUE TITLE
Inaccurate categories

### ISSUE THREAD

**Issue by ibrahimchiha** [niklasamslgruber/EmojiKit#4]
The categories provided do not match the system categories (I'm on iOS 17):

1. `Smileys & Emotion` should be renamed to `Smileys & People`.
2. `People & Body` should be merged with `Smileys & People`.
3. `Activities` should be renamed to `Activity`.
4. I think `Component` category should be removed.

Let me know if you'd like me to contribute to this repository directly or if you can handle the fixes

**Comment by niklasamslgruber** [comment]
Hi @ibrahimchiha, thanks for the info. I will release a new version with the fixes tomorrow.

**Comment by niklasamslgruber** [comment]
Fixed in [v1.2.1](https://github.com/niklasamslgruber/EmojiKit/releases/tag/v1.2.1)
